import { createFileRoute, Link } from "@tanstack/react-router";
import { Mail, FileText, ListChecks, Search, MessageSquare, ArrowRight, Sparkles } from "lucide-react";
import { AppShell } from "@/components/AppShell";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Workplace AI — Productivity Assistant" },
      { name: "description", content: "Automate emails, meeting notes, tasks, and research with AI built for professionals." },
    ],
  }),
  component: Index,
});

const tools = [
  { url: "/email", icon: Mail, title: "Smart Email Generator", desc: "Draft polished emails from a few bullet points." },
  { url: "/notes", icon: FileText, title: "Meeting Notes Summarizer", desc: "Turn transcripts into clean summaries and action items." },
  { url: "/tasks", icon: ListChecks, title: "AI Task Planner", desc: "Break down goals into prioritized, scheduled tasks." },
  { url: "/research", icon: Search, title: "AI Research Assistant", desc: "Get briefings, key facts, and source-aware overviews." },
  { url: "/chat", icon: MessageSquare, title: "AI Chatbot", desc: "Ask anything — your always-on workplace copilot." },
] as const;

function Index() {
  return (
    <AppShell title="Dashboard" description="Your AI-powered workplace command center">
      <section className="rounded-2xl bg-gradient-primary p-8 text-primary-foreground shadow-elegant relative overflow-hidden">
        <div className="absolute -top-12 -right-12 h-48 w-48 rounded-full bg-white/10 blur-2xl" />
        <div className="relative max-w-2xl">
          <div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-medium">
            <Sparkles className="h-3.5 w-3.5" /> Powered by Lovable AI
          </div>
          <h2 className="mt-4 text-3xl font-semibold tracking-tight">
            Get more done with your AI workplace assistant
          </h2>
          <p className="mt-2 text-primary-foreground/85">
            Five focused tools that handle the busywork — so you can spend time on what matters.
          </p>
          <Link
            to="/chat"
            className="mt-5 inline-flex items-center gap-2 rounded-lg bg-background text-foreground px-4 py-2 text-sm font-medium hover:bg-background/90 transition-colors"
          >
            Open AI Chat <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </section>

      <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {tools.map((t) => (
          <Link
            key={t.url}
            to={t.url}
            className="group rounded-xl border border-border bg-card p-5 shadow-card hover:shadow-elegant hover:-translate-y-0.5 transition-all"
          >
            <div className="h-10 w-10 rounded-lg bg-accent text-accent-foreground flex items-center justify-center mb-3 group-hover:bg-gradient-primary group-hover:text-primary-foreground transition-colors">
              <t.icon className="h-5 w-5" />
            </div>
            <div className="font-semibold">{t.title}</div>
            <p className="text-sm text-muted-foreground mt-1">{t.desc}</p>
            <div className="mt-4 inline-flex items-center text-sm text-primary font-medium">
              Open <ArrowRight className="h-4 w-4 ml-1 group-hover:translate-x-0.5 transition-transform" />
            </div>
          </Link>
        ))}
      </section>

      <section className="mt-8 rounded-xl border border-border bg-card p-5 shadow-card">
        <h3 className="font-semibold">Responsible AI</h3>
        <p className="text-sm text-muted-foreground mt-1">
          Outputs are generated by AI models and may contain errors or bias. Review and edit before
          using in production communication. Avoid submitting confidential or regulated data.
        </p>
      </section>
    </AppShell>
  );
}
