import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useMutation } from "@tanstack/react-query";
import { toast } from "sonner";
import { Search, Loader2 } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { AiOutput } from "@/components/AiOutput";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { generateAi } from "@/lib/ai/generate.functions";

export const Route = createFileRoute("/research")({
  head: () => ({ meta: [{ title: "AI Research Assistant — Workplace AI" }] }),
  component: ResearchPage,
});

function ResearchPage() {
  const [topic, setTopic] = useState("");
  const [depth, setDepth] = useState("Briefing");
  const [output, setOutput] = useState("");
  const fn = useServerFn(generateAi);

  const mut = useMutation({
    mutationFn: async () => {
      const system = `You are a workplace research assistant. Produce a ${depth.toLowerCase()} on the topic. Structure: Overview, Key Facts (bullets), Recent Trends, Considerations / Risks, Suggested Next Steps. Be neutral and concise. When unsure, say so. Do NOT fabricate citations.`;
      const res = await fn({ data: { system, prompt: `Topic / question:\n${topic}` } });
      return res.content;
    },
    onSuccess: (c) => setOutput(c),
    onError: (e: Error) => toast.error(e.message),
  });

  return (
    <AppShell title="AI Research Assistant" description="Briefings, key facts, and overviews">
      <div className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-xl border border-border bg-card p-5 shadow-card space-y-4">
          <div className="flex items-center gap-2 text-sm font-medium">
            <Search className="h-4 w-4 text-primary" /> Research request
          </div>
          <div className="grid gap-2">
            <Label>Topic or question</Label>
            <Textarea rows={6} value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Compare the top 3 project management tools for distributed teams in 2025." />
          </div>
          <div className="grid gap-2">
            <Label>Depth</Label>
            <Select value={depth} onValueChange={setDepth}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["Quick summary", "Briefing", "Deep dive"].map((d) => (
                  <SelectItem key={d} value={d}>{d}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <Button
            className="w-full bg-gradient-primary text-primary-foreground shadow-elegant"
            disabled={mut.isPending || !topic.trim()}
            onClick={() => mut.mutate()}
          >
            {mut.isPending ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
            Research
          </Button>
          <p className="text-[11px] text-muted-foreground">
            ⚠️ Research is generated by AI without live web access. Verify critical facts against
            primary sources.
          </p>
        </div>
        <AiOutput value={output} onChange={setOutput} loading={mut.isPending} filename="research" />
      </div>
    </AppShell>
  );
}
